esphome:
  name: me007ys-esp32c3
  friendly_name: ME007YS Example ESP32-C3

external_components:
  - source:
      type: local
      path: ./external_components
    components: [me007ys]

logger:
  level: DEBUG

uart:
  id: uart_me007ys
  tx_pin: GPIO1      # ESP TX → sensor RX
  rx_pin: GPIO3      # ESP RX ← sensor TX
  baud_rate: 9600
  rx_buffer_size: 256

sensor:
  - platform: me007ys
    uart_id: uart_me007ys
    name: "Water Level Distance (cm)"
    id: distance_cm
    update_interval: 500ms
    min_valid_cm: 28.0
    max_valid_cm: 450.0
    too_close_behavior: nan
    guard_cm: 12.0
    max_step_cm: 120.0
    require_consecutive: 3
    frame_rate_hz:
      name: "ME007YS Frame Rate"
      entity_category: diagnostic
    status:
      name: "ME007YS Status"
      entity_category: diagnostic
    raw_mm:
      name: "ME007YS Raw Distance (mm)"
      entity_category: diagnostic
    raw_mm_policy: valid_only

  # Inches view that stays in sync with cm (Option A)
  - platform: template
    name: "Water Level Distance (in)"
    id: distance_in
    unit_of_measurement: "in"
    accuracy_decimals: 2
    update_interval: 500ms
    lambda: |-
      if (isnan(id(distance_cm).state)) return NAN;
      return id(distance_cm).state * 0.393701;
