esphome:
  name: me007ys_sensor
  friendly_name: ME007YS Sensor

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

external_components:
  - source: github://YOUR_GITHUB_USERNAME/esphome-me007ys-sensor
    components: [me007ys]

logger:
  level: DEBUG
  logs:
    me007ys: VERY_VERBOSE   # set VERY_VERBOSE only if debug_raw: true

api:
ota:
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

uart:
  id: uart_me007ys
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600
  rx_buffer_size: 256

sensor:
  - platform: me007ys
    uart_id: uart_me007ys
    name: "Water Level Distance (cm)"
    id: water_level_cm
    update_interval: 500ms
    min_valid_mm: 280
    too_close_behavior: min      # nan | min | last
    debug_raw: false
    frame_rate_hz:
      name: "ME007YS Frame Rate"
      entity_category: diagnostic
    status:
      name: "ME007YS Status"
      entity_category: diagnostic

  - platform: template
    name: "Water Level Distance (in)"
    unit_of_measurement: "in"
    accuracy_decimals: 2
    lambda: |-
      if (isnan(id(water_level_cm).state)) return NAN;
      return id(water_level_cm).state * 0.393701;
    update_interval: 500ms
