esphome:
  name: me007ys-esp32c3
  friendly_name: ME007YS Example ESP32-C3

external_components:
  - source: github://YOUR_GITHUB_USERNAME/esphome-me007ys-sensor
    components: [me007ys]

uart:
  id: uart_me007ys
  tx_pin: GPIO1      # ESP TX → sensor RX
  rx_pin: GPIO3      # ESP RX ← sensor TX
  baud_rate: 9600
  rx_buffer_size: 256

sensor:
  - platform: me007ys
    uart_id: uart_me007ys
    name: "Water Level Distance (cm)"
    id: water_level_cm
    update_interval: 500ms
    min_valid_cm: 28.0       # default 28.0 cm
    max_valid_cm: 450.0      # default 450.0 cm
    too_close_behavior: min  # nan | min | last
    too_far_behavior: max    # nan | max | last
    debug_raw: false
    frame_rate_hz:
      name: "ME007YS Frame Rate"
      entity_category: diagnostic
    status:
      name: "ME007YS Status"
      entity_category: diagnostic

  # Optional: inches conversion
  - platform: template
    name: "Water Level Distance (in)"
    unit_of_measurement: "in"
    accuracy_decimals: 2
    lambda: |-
      if (isnan(id(water_level_cm).state)) return NAN;
      return id(water_level_cm).state * 0.393701;
